### ISSUE TITLE
Und- Flowkarte

### ISSUE THREAD

**Issue by SamCan92** [spkesDE/com.spkes.openMeteo#1]
Ciao Julian

Wäre es möglich, das Wetter auch als "Und"-Flowkarte nutzen zu können?

Bsp.: WENN es 07:00 ist UND die Regenwahrscheinlichkeit bei unter 50% liegt, DANN wässere den Rasen.

Vielen Dank für's checken und liebe Grüsse aus der CH

Cheers
Sam

**Comment by spkesDE** [comment]
Kannst du bereits mit den Logik karten machen.
![image](https://github.com/spkesDE/com.spkes.openMeteo/assets/1682314/f990712f-5ce9-4698-9111-ad02ccea0fe8)

**Comment by SamCan92** [comment]
Mein Held, danke! Sorry, hab den Homey seit 3 Tagen und bin noch etwas unbeholfen
